### ISSUE TITLE
Combine dynamic manager with path planner

### ISSUE THREAD

**Issue by threewisemonkeys-as** [ERC-BPGC/Trotbot#31]
This will result in a single node which 
- Subscribes to `odom` and `obstacles`
- Publishes `cmd_vel` 

`obstacle_collision_check` will be called at certain intervals. It will call `path_plan` whenever it finds collision. 

`control_vel` will be called at certain intervals which computes `cmd_vel` according to first point in the path and publishes it.

**Comment by SuhrudhSarathy** [comment]
There are some changes
1.  The ```dynamic manager``` subscribes to ```odom``` and ```obstacles``` and publishes a ```path``` message.
2. The controller subscribes to ```path``` message and publishes ```cmd_vel```.

**Comment by hardesh** [comment]
@SuhrudhSarathy create a pull request and mention that PR in this issue

**Comment by SuhrudhSarathy** [comment]
Further changes made are as follows:
1. Made dynamic manager compatible with gennav
2. Modified some aspects of the controller
3. Modified the collision function to take into account the width of the robot (Experimental)
